### ISSUE TITLE
User Story Template

### ISSUE THREAD

**Issue by JessicaLoers** [JessicaLoers/capstone-project-super-app#1]
## Value proposition

**As an**  `ROLE`
**I want a**  `ACTIVITY`
**So that**  `DESIRED USER VALUE`

## Description

- Scribble / design or text
- Precise, no unnecessary information

## Acceptance criteria

- [ ] What happens when an entry is empty?
- [ ] How should something behave?
- [ ] What is the text of an alert?

## Tasks
- [ ] Do something
